pipeline:
  name: s3
  identifier: s3
  projectIdentifier: poc
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: upload
        identifier: upload
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: FilesUpload
                  name: FilesUpload_1
                  identifier: FilesUpload_1
                  spec: {}
                  timeout: 30m
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          curl --location 'https://app.harness.io/gateway/pipeline/api/input-file/download-file?accountIdentifier=ACCOUNT_IDENTIFIER&filePath=FILE_PATH' \
                          --header 'x-api-key: PAT_TOKEN'
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  properties:
    ci:
      codebase:
        connectorRef: git
        repoName: <+input>
        build: <+input>
