pipeline:
  name: s3
  identifier: s3
  projectIdentifier: poc
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: file-upload
        identifier: fileupload
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: FilesUpload
                  name: FilesUpload_1
                  identifier: FilesUpload_1
                  spec: {}
                  timeout: 30m
          environment:
            environmentRef: dev
            deployToAll: false
        tags: {}
