pipeline:
  name: s3
  identifier: s3
  projectIdentifier: poc
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: file-upload
        identifier: fileupload
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Email
                  name: Email_1
                  identifier: Email_1
                  spec:
                    to: mayankat2299@gmail.com
                    cc: mayank2299@gmail.com
                    subject: Hello harness
                    body: Hii from harness ci-cd
                  timeout: 10m
          environment:
            environmentRef: dev
            deployToAll: false
        tags: {}
