pipeline:
  name: s3
  identifier: s3
  projectIdentifier: poc
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: file-upload
        identifier: fileupload
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: FilesUpload
                  name: FilesUpload_1
                  identifier: FilesUpload_1
                  spec: {}
                  timeout: 30m
              - step:
                  type: ShellScript
                  name: s3 push
                  identifier: s3_push
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: aws s3 ls
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
          environment:
            environmentRef: dev
            deployToAll: false
        tags: {}
