version: 2.1

orbs:
  terraform: "circleci/terraform@1.1.0"

jobs:
  plan_job:
    executor: terraform/default
    steps:
      - checkout
      - run:
          name: Configure AWS CLI and S3 Backend
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            terraform init -backend-config="bucket=$TF_BUCKET" -backend-config="key=$TF_STATE_KEY" -backend-config="region=$TF_REGION"
      - run:
          name: Plan Infrastructure
          command: terraform plan example

  apply_job:
    executor: terraform/default
    steps:
      - checkout
      - run:
          name: Configure AWS CLI and S3 Backend
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            terraform init -backend-config="bucket=$TF_BUCKET" -backend-config="key=$TF_STATE_KEY" -backend-config="region=$TF_REGION"
      - run:
          name: Apply Infrastructure
          command: terraform apply ./terraform-aws-arc-kms/example

workflows:
  version: 2
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          path: ./terraform-aws-arc-kms/example/main.tf
          context: terraform
      - terraform/validate:
          path: example
          context: terraform
          requires:
            - terraform/fmt
      - plan_job:
          requires:
            - terraform/validate
      - apply_job:
          requires:
            - terraform/validate
