version: 2
jobs:
  plan:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /example
    steps:
      - checkout
      - run:
          name: Init
          command: terraform init -input=false
      - run:
          name: Plan
          command: terraform plan -input=false -out=tfplan -no-color
      - run:
          name: Render plan for PR comment
          command: terraform show -no-color tfplan > tfplan.txt
      - persist_to_workspace:
          root: /example
          paths:
            - ./example

  apply:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /example
    steps:
      - attach_workspace:
          at: /example
      - run:
          name: Apply
          command: terraform apply tfplan

  plan_comment:
    docker:
      - image: cloudposse/github-commenter:latest
    working_directory: /code
    steps:
      - checkout
      - attach_workspace:
          at: /example
      - run:
          name: Post plan to PR comment
          command: |-
            export CIRCLE_PR_NUMBER=${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}
            if [ -z $CIRCLE_PR_NUMBER ]; then echo "Not a pull request - aborting"; exit 0; fi
            cat /code/tfplan.txt | github-commenter \
              -owner ${CIRCLE_PROJECT_USERNAME} \
              -repo ${CIRCLE_PROJECT_REPONAME} \
              -number $CIRCLE_PR_NUMBER \
              -delete-comment-regex "Output from" \
              -type pr \
              -template_file /code/.circleci/plan-comment.tpl
workflows:
  version: 2
  plan_pr:
    jobs:
      - plan
      - plan_comment:
          requires:
            - plan
          filters:
            branches:
              ignore: main
      - hold-apply:
          type: approval
          requires:
            - plan        
      - apply:
          requires:
            - hold-apply
          filters:
            branches:
              only: main
